# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Janus' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '9.3'

  # Pods for Janus
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
end
